// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProtocol.proto

package com.demo.netty.demo.rpc.protocol.protobuf;

public final class MessagePOJO {
  private MessagePOJO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用 data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.Message.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <pre>
     *用 data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.Message.DataType data_type = 1;</code>
     * @return The dataType.
     */
    com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType getDataType();

    /**
     * <code>.RequestMessage request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>.RequestMessage request = 2;</code>
     * @return The request.
     */
    com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage getRequest();
    /**
     * <code>.RequestMessage request = 2;</code>
     */
    com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder getRequestOrBuilder();

    /**
     * <code>.ResponseMessage response = 3;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.ResponseMessage response = 3;</code>
     * @return The response.
     */
    com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage getResponse();
    /**
     * <code>.ResponseMessage response = 3;</code>
     */
    com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder getResponseOrBuilder();

    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   *protobuf 可以使用 message 管理其他的 message
   * </pre>
   *
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.class, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.Builder.class);
    }

    /**
     * <pre>
     *定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code Message.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *在 proto3 要求 enum 的编号从 0 开始
       * </pre>
       *
       * <code>RequestMessage = 0;</code>
       */
      RequestMessage(0),
      /**
       * <code>ResponseMessage = 1;</code>
       */
      ResponseMessage(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *在 proto3 要求 enum 的编号从 0 开始
       * </pre>
       *
       * <code>RequestMessage = 0;</code>
       */
      public static final int RequestMessage_VALUE = 0;
      /**
       * <code>ResponseMessage = 1;</code>
       */
      public static final int ResponseMessage_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return RequestMessage;
          case 1: return ResponseMessage;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      REQUEST(2),
      RESPONSE(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return REQUEST;
          case 3: return RESPONSE;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *用 data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.Message.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *用 data_type 来标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.Message.DataType data_type = 1;</code>
     * @return The dataType.
     */
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType result = com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType.valueOf(dataType_);
      return result == null ? com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType.UNRECOGNIZED : result;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    /**
     * <code>.RequestMessage request = 2;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.RequestMessage request = 2;</code>
     * @return The request.
     */
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage getRequest() {
      if (dataBodyCase_ == 2) {
         return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_;
      }
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
    }
    /**
     * <code>.RequestMessage request = 2;</code>
     */
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder getRequestOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_;
      }
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>.ResponseMessage response = 3;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.ResponseMessage response = 3;</code>
     * @return The response.
     */
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage getResponse() {
      if (dataBodyCase_ == 3) {
         return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_;
      }
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
    }
    /**
     * <code>.ResponseMessage response = 3;</code>
     */
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder getResponseOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_;
      }
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType.RequestMessage.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType.RequestMessage.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message)) {
        return super.equals(obj);
      }
      com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message other = (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getRequest()
              .equals(other.getRequest())) return false;
          break;
        case 3:
          if (!getResponse()
              .equals(other.getResponse())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + REQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getRequest().hashCode();
          break;
        case 3:
          hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protobuf 可以使用 message 管理其他的 message
     * </pre>
     *
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.class, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.Builder.class);
      }

      // Construct using com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message getDefaultInstanceForType() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message build() {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message buildPartial() {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message result = new com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (requestBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = requestBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (responseBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = responseBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message) {
          return mergeFrom((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message other) {
        if (other == com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *用 data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.Message.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *用 data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.Message.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用 data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.Message.DataType data_type = 1;</code>
       * @return The dataType.
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType result = com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType.valueOf(dataType_);
        return result == null ? com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *用 data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.Message.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用 data_type 来标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.Message.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder> requestBuilder_;
      /**
       * <code>.RequestMessage request = 2;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       * @return The request.
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage getRequest() {
        if (requestBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_;
          }
          return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return requestBuilder_.getMessage();
          }
          return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      public Builder setRequest(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      public Builder setRequest(
          com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder builderForValue) {
        if (requestBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      public Builder mergeRequest(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage value) {
        if (requestBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance()) {
            dataBody_ = com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.newBuilder((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder getRequestOrBuilder() {
        if ((dataBodyCase_ == 2) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_;
          }
          return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.RequestMessage request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder>(
                  (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return requestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder> responseBuilder_;
      /**
       * <code>.ResponseMessage response = 3;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       * @return The response.
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage getResponse() {
        if (responseBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_;
          }
          return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return responseBuilder_.getMessage();
          }
          return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      public Builder setResponse(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      public Builder setResponse(
          com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder builderForValue) {
        if (responseBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      public Builder mergeResponse(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage value) {
        if (responseBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance()) {
            dataBody_ = com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.newBuilder((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder getResponseOrBuilder() {
        if ((dataBodyCase_ == 3) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_;
          }
          return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.ResponseMessage response = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder>(
                  (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return responseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message();
    }

    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *接口名
     * </pre>
     *
     * <code>string className = 1;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <pre>
     *接口名
     * </pre>
     *
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <pre>
     *参数
     * </pre>
     *
     * <code>string param = 2;</code>
     * @return The param.
     */
    java.lang.String getParam();
    /**
     * <pre>
     *参数
     * </pre>
     *
     * <code>string param = 2;</code>
     * @return The bytes for param.
     */
    com.google.protobuf.ByteString
        getParamBytes();

    /**
     * <pre>
     *方法名
     * </pre>
     *
     * <code>string method = 3;</code>
     * @return The method.
     */
    java.lang.String getMethod();
    /**
     * <pre>
     *方法名
     * </pre>
     *
     * <code>string method = 3;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();
  }
  /**
   * Protobuf type {@code RequestMessage}
   */
  public  static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMessage)
      RequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMessage() {
      className_ = "";
      param_ = "";
      method_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              param_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_RequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.class, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder.class);
    }

    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object className_;
    /**
     * <pre>
     *接口名
     * </pre>
     *
     * <code>string className = 1;</code>
     * @return The className.
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接口名
     * </pre>
     *
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAM_FIELD_NUMBER = 2;
    private volatile java.lang.Object param_;
    /**
     * <pre>
     *参数
     * </pre>
     *
     * <code>string param = 2;</code>
     * @return The param.
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        param_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *参数
     * </pre>
     *
     * <code>string param = 2;</code>
     * @return The bytes for param.
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 3;
    private volatile java.lang.Object method_;
    /**
     * <pre>
     *方法名
     * </pre>
     *
     * <code>string method = 3;</code>
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *方法名
     * </pre>
     *
     * <code>string method = 3;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
      }
      if (!getParamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, param_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
      }
      if (!getParamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, param_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage)) {
        return super.equals(obj);
      }
      com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage other = (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) obj;

      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getParam()
          .equals(other.getParam())) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + PARAM_FIELD_NUMBER;
      hash = (53 * hash) + getParam().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMessage)
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.class, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.Builder.class);
      }

      // Construct using com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        className_ = "";

        param_ = "";

        method_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage getDefaultInstanceForType() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage build() {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage buildPartial() {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage result = new com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage(this);
        result.className_ = className_;
        result.param_ = param_;
        result.method_ = method_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) {
          return mergeFrom((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage other) {
        if (other == com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage.getDefaultInstance()) return this;
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.getParam().isEmpty()) {
          param_ = other.param_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <pre>
       *接口名
       * </pre>
       *
       * <code>string className = 1;</code>
       * @return The className.
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接口名
       * </pre>
       *
       * <code>string className = 1;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接口名
       * </pre>
       *
       * <code>string className = 1;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接口名
       * </pre>
       *
       * <code>string className = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接口名
       * </pre>
       *
       * <code>string className = 1;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object param_ = "";
      /**
       * <pre>
       *参数
       * </pre>
       *
       * <code>string param = 2;</code>
       * @return The param.
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          param_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *参数
       * </pre>
       *
       * <code>string param = 2;</code>
       * @return The bytes for param.
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *参数
       * </pre>
       *
       * <code>string param = 2;</code>
       * @param value The param to set.
       * @return This builder for chaining.
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数
       * </pre>
       *
       * <code>string param = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParam() {
        
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数
       * </pre>
       *
       * <code>string param = 2;</code>
       * @param value The bytes for param to set.
       * @return This builder for chaining.
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        param_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <pre>
       *方法名
       * </pre>
       *
       * <code>string method = 3;</code>
       * @return The method.
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *方法名
       * </pre>
       *
       * <code>string method = 3;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *方法名
       * </pre>
       *
       * <code>string method = 3;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *方法名
       * </pre>
       *
       * <code>string method = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *方法名
       * </pre>
       *
       * <code>string method = 3;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
    private static final com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage();
    }

    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
      @java.lang.Override
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.RequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 1;</code>
     * @return The response.
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 1;</code>
     * @return The bytes for response.
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code ResponseMessage}
   */
  public  static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseMessage)
      ResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessage() {
      response_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              response_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_ResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.class, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private volatile java.lang.Object response_;
    /**
     * <code>string response = 1;</code>
     * @return The response.
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 1;</code>
     * @return The bytes for response.
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage)) {
        return super.equals(obj);
      }
      com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage other = (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) obj;

      if (!getResponse()
          .equals(other.getResponse())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseMessage)
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_ResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.class, com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.Builder.class);
      }

      // Construct using com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        response_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.internal_static_ResponseMessage_descriptor;
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage getDefaultInstanceForType() {
        return com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage build() {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage buildPartial() {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage result = new com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage(this);
        result.response_ = response_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) {
          return mergeFrom((com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage other) {
        if (other == com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage.getDefaultInstance()) return this;
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 1;</code>
       * @return The response.
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       * @return The bytes for response.
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       * @param value The bytes for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        response_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:ResponseMessage)
    private static final com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage();
    }

    public static com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
      @java.lang.Override
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.netty.demo.rpc.protocol.protobuf.MessagePOJO.ResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MessageProtocol.proto\"\272\001\n\007Message\022$\n\td" +
      "ata_type\030\001 \001(\0162\021.Message.DataType\022\"\n\007req" +
      "uest\030\002 \001(\0132\017.RequestMessageH\000\022$\n\010respons" +
      "e\030\003 \001(\0132\020.ResponseMessageH\000\"3\n\010DataType\022" +
      "\022\n\016RequestMessage\020\000\022\023\n\017ResponseMessage\020\001" +
      "B\n\n\010dataBody\"B\n\016RequestMessage\022\021\n\tclassN" +
      "ame\030\001 \001(\t\022\r\n\005param\030\002 \001(\t\022\016\n\006method\030\003 \001(\t" +
      "\"#\n\017ResponseMessage\022\020\n\010response\030\001 \001(\tB:\n" +
      ")com.demo.netty.demo.rpc.protocol.protob" +
      "ufB\013MessagePOJOH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "DataType", "Request", "Response", "DataBody", });
    internal_static_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMessage_descriptor,
        new java.lang.String[] { "ClassName", "Param", "Method", });
    internal_static_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMessage_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
